name: Test workflow dispatch

on:
  workflow_dispatch:
    inputs:
      # name:
      #   type: choice
      #   description: Who to greet
      #   options:
      #     - monalisa
      #     - cschleiden
      # message:
      #   required: true
      deployApi:
        type: boolean
        description: Deploy the API app
        default: true
      deployFrontend:
        type: boolean
        description: Deploy the Frontend app
        default: true
      deployTunnel:
        type: boolean
        description: Deploy the Tunnel app
        default: true
      # environment:
      #   type: environment

jobs:
  api:
    if: github.event.inputs.deployApi == true
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "API Deployed"

  frontend:
    if: github.event.inputs.deployFrontend == true
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Frontend Deployed"

  tunnel:
    if: github.event.inputs.deployTunnel == true
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Tunnel Deployed"
