name: Test workflow dispatch

on:
  workflow_dispatch:
    inputs:
      # name:
      #   type: choice
      #   description: Who to greet
      #   options:
      #     - monalisa
      #     - cschleiden
      # message:
      #   required: true
      deployAPI:
        type: boolean
        description: Deploy the API app
        default: true
      deployFrontend:
        type: boolean
        description: Deploy the Frontend app
        default: true
      deployTunnel:
        type: boolean
        description: Deploy the Tunnel app
        default: true
      # environment:
      #   type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "test - ${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
