name: Test workflow dispatch

on:
  workflow_dispatch:
    inputs:
      deployApi:
        type: boolean
        description: Deploy the API app
        default: true
      deployFrontend:
        type: boolean
        description: Deploy the Frontend app
        default: true
      deployTunnel:
        type: boolean
        description: Deploy the Tunnel app
        default: true
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - test
          - staging
          - demo
          - production

jobs:
  log-inputs:
    name: Log workflow inputs
    runs-on: ubuntu-latest

    steps:
      - name: Log inputs
        run: |
          echo "DeployApi - ${{ inputs.deployApi }}"
          echo "DeployFrontend - ${{ inputs.DeployFrontend }}"
          echo "DeployTunnel - ${{ inputs.deployTunnel }}"
          echo "Environment - ${{ inputs.environment }}"
  api:
    if: ${{ inputs.deployApi }}
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "API deployed to ${{ inputs.environment }}"

  frontend:
    if: ${{ inputs.deployFrontend }}
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Frontend deployed to ${{ inputs.environment }}"

  tunnel:
    if: ${{ inputs.deployTunnel }}
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Tunnel deployed to ${{ inputs.environment }}"
